# user/.github/workflows/ci.yml

name: Service CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test
      MYSQL_ROOT_PASSWORD: root
      USER_DATABASE_URL: mysql://root:root@127.0.0.1:3330/app_db

    services:
      mysql:
        image: mysql:8.3
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: app_db
        ports:
          - 3330:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -p${MYSQL_ROOT_PASSWORD} --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20 LTS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install --no-audit --no-fund

      - name: Prisma generate (native engines)
        run: npm run prisma:generate

      - name: Wait for MySQL to be ready
        run: |
          sudo apt-get update -y
          sudo apt-get install -y mysql-client
          for i in {1..60}; do
            if mysqladmin ping -h 127.0.0.1 -P 3330 -uroot -p"${MYSQL_ROOT_PASSWORD}" --silent; then
              echo "MySQL is up"; break
            fi
            echo "Waiting for MySQL ($i/60)"; sleep 2
          done

      - name: Reset DB and apply migrations
        run: node ./scripts/prisma.mjs migrate reset --force --skip-seed

      - name: Build
        run: npm run build

      - name: Test (CI mode)
        run: npm run test:ci
